version: '3.3'
services:
  database:
    image: postgres:15.1
    environment:    
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=cHJLLU23491'
      - 'POSTGRES_DB=postgres'
    ports:
      - 5441:5432
    volumes:
      - pg-data:/var/lib/postgres/data
volumes:
  pg-data:
 
    
  